### ISSUE TITLE
FR: widget support

### ISSUE THREAD

**Issue by el-schneider** [jackabox/statamic-plausible-analytics#2]
Hey Jack, did you consider providing widgets? I think analytics would fit perfectly in the dashboard area.

I sure would be really happy :-)

**Comment by jackabox** [comment]
Hey, It's on my list of nice features, but it wasn't crucial when getting it out.

What kind of widgets would you want?

**Comment by el-schneider** [comment]
Actually I think each of the boxes that are now at `/cp/analytics` would make for a nice widget. But i also wouldn't mind if just all of it together could be displayed as a widget. It's mostly about making the not-so-useful `dashboard` a bit more useful
