### ISSUE TITLE
Transfer local installation to production server

### ISSUE THREAD

**Issue by marflow** [jackabox/statamic-plausible-analytics#3]
Hello Jack, thanks for the addon! I installed it locally with Composer and everything is working fine, I see the plausible data for the live site. Then I committed the files and transferred them with gitftp to the live site, but the addon is not listed as installed. Jackabox vendor folder with plausible subfolder, plausible.php, config.php and .env with details are all in place.

Would you have an idea what might be the problem?
Thanks!

**Comment by jackabox** [comment]
Hey @marflow, as long as you have all of the vendor files (including an updated autoload) and the .env then everything should work. Chances are something hasn't been copied across with your vendor (always resync the whole folder if not using a command line)

**Comment by marflow** [comment]
Hello Jack, 
I´ve found my issue: I had gitignored the files in `bootstrap/cache` folder, so the plugin was not loaded on the live site. All good now. Sorry for bothering you and thanks again for the plugin!
