### ISSUE TITLE
regression: custom domains no longer supported

### ISSUE THREAD

**Issue by ryanmitchell** [jackabox/statamic-plausible-analytics#6]
In the 1.2 update you regressed the custom domains support... e.g.
https://github.com/jackabox/statamic-plausible-analytics/blob/fc09c82de1c8f86c8fff5a4824f0de12c9dd5fce/src/Http/Controllers/Api/AggregatesController.php#L39

**Comment by jackabox** [comment]
@ryanmitchell Should be rectified in 1.2.1. Not sure what happened there!

**Comment by ryanmitchell** [comment]
Thank you!
